var allQuestions = [
  { question: '1 + 1', answer: ['2'], hint: 'Hey common now, you got this :-)' },
  { question: 'Blue + Yellow', answer: ['Green', 'green'], hint: 'Go back to middle school' },
  { question: 'H2O', answer: ['Water'], hint: 'Really? There is no way you can not get this one' },
  { question: 'C3PO', answer: ['R2D2'], hint: 'Star Wars astromech droid' },
  { question: 'NO', answer: ['Yes'], hint: 'Its opposite day!' },
  { question: 'I WIll BE BACK', answer: ['Terminator'], hint: 'Killer robots from the future' },
  { question: 'What is realy misin', answer: ['Lsg'], hint: 'Some letters are not there' },
  { question: '8 13 21 34 55 89', answer: ['144'], hint: 'Add some numbers' },
  { question: 'Tomato + Vodka + Tabasco', answer: ['Bloodymary'], hint: 'Its a drink and its one word' },
  { question: 'Type Here', answer: ['Here'], hint: 'Have you tried typing here?' },
  { question: 'The Ultimate Question Of Life The Universe And Everything', answer: ['42'], hint: "The Ultimate Hitchhiker's Guide to the Galaxy" },
  { question: 'Hello JJK RINGG', answer: ['55574644'], hint: 'Have you used flip phone for texting?' },
  { question: 'Awa Par Ban Coo', answer: ['King'], hint: 'Cooking? Banking? Parking?' },
  { question: 'Water + 32 F', answer: ['Ice'], hint: 'Water turns into _ _ _?' },
  { question: 'P + Left Step 1 + Left Step 7 + Right Step 1 + Right Step 1', answer: ['Power'], hint: 'Take a walk on your keyboard' },
  { question: 'Thats My Spot', answer: ['Sheldon'], hint: 'The Big Bang Theory character name' },
  { question: 'Romeo Echo Juliet Echo Charlie Tango', answer: ['Reject'], hint: 'Military Alphabet' },
  { question: 'Squize Red + Yellow', answer: ['Orange Juice'], hint: 'What color does red and yellow make' },
  { question: 'We Were On Break', answer: ['Friends'], hint: 'Its a popular show name with a Ross' },
  { question: '15 30 40 Game', answer: ['Tennis'], hint: 'Its a racket game' },
  { question: 'Its My Birthday', answer: ['Happy Birthday'], hint: "What do you say when its someone's birthday" },
  { question: 'Wovsimr Moabiwl', answer: ['Mirror'], hint: 'Something reflexive' },
  { question: 'Legend Cocktail Vanilla Sky', answer: ['Tomcruise'], hint: 'Movie Star with a tooth in middle' },
  { question: 'Reverse', answer: ['Esrever none* Answers'], hint: 'Have you tried writing in reverse?' },
  { question: '#000000 Pandora Opens', answer: ['Airplane'], hint: 'Color and a box' },
  { question: 'Nag A Ram', answer: ['Anagram'], hint: 'Its an anagram' },
  { question: 'The Cat Is Not Dead', answer: ['Schrodinger'], hint: 'Or is the cat dead?' },
  { question: 'The Answer Is Next The Next Is Answer', answer: ['Next'], hint: 'Literally what it says' },
  { question: 'Next', answer: ['Answer'], hint: 'Do you remember the last question?' },
  { question: 'From B1 I Can Go To A3 D2 C3', answer: ['Knight or Horse'], hint: 'Think of chess' },
  { question: '-.-.—-…', answer: ['Morse'], hint: 'Its a type of code' },
  { question: '33 + 94 + ?', answer: ['53'], hint: 'Degrees in a triangle' },
  { question: 'O degree', answer: ['360'], hint: 'How many degrees in a circle' },
  { question: 'If This Level Is Oc Answer Is 63633N', answer: ['Cocoon'], hint: 'The level is 36' },
  { question: 'Ppppppp rkbqkbkr', answer: ['Chess'], hint: 'Think of pawns, rooks, kings, and queens' },
  { question: 'Dont Judge By The Cover 0930289234', answer: ['Watchmen'], hint: 'Its an isbn number' },
  { question: 'Spaceships', answer: ['Starwars'], hint: 'Death Star, Executor, Imperial landing craft, Imperial shuttle' },
  { question: 'Draw Up2 Left1 Up1 Right 0.5 Down 0.5 Right 0.5 Up2 Right 0.5 Down 1 Right 0.5 Up 0.5 Down 1 Left 1 Down 3', answer: ['Cactus'], hint: 'Try drawing' },
  { question: 'Red 1 Yellow 2 Green 3 Bron 4 Blues Pink6 Black 7 I Love This Game', answer: ['Snooker'], hint: 'Its a game with balls of these colors' },
  { question: '14 February – Valets', answer: ['Nine'], hint: 'We are missing letters' },
  { question: 'Up 384 403 Down 20000', answer: ['Julesverne'], hint: 'Around the world in ___ days, ___ leagues under the sea, Journey to the center of the earth' },
  { question: 'Now The Hungry Lion Roars And The Wolf Behowls The Moon Whilst The Heavy Ploughman Snores', answer: ['Wisdom'], hint: 'row - word - letter' },
  { question: 'Avles Al Ed Yer', answer: ['Lion'], hint: 'Reverse the letters and translate from spanish' },
  { question: 'XXI VII MCMLXIX', answer: ['Moonlanding or Moon'], hint: 'It is a date' },
  { question: 'NY 3,14', answer: ['Applepie'], hint: 'I have faith in you' },
  { question: 'oooOoooo', answer: ['Mars'], hint: 'These are planets' }
];
