var questionArray = [
  '1 + 1',
  'Blue + Yellow',
  'H2O',
  'C3PO',
  'NO',
  'I WIll BE BACK',
  'What is really misin',
  '8 13 21 34 55 89',
  'Tomato + Vodka + Tabasco',
  'Type Here',
  'The Ultimate Question Of Life The Universe And Everything',
  'Hello JJK RINGG',
  'Awa Par Ban Coo',
  'Water + 32 F',
  'P + Left Step 1 + Left Step 7 + Right Step 1 + Right Step 1',
  'Thats My Spot',
  'Romeo Echo Juliet Echo Charlie Tango',
  'Squize Red + Yellow',
  'We Were On Break',
  '15 30 40 Game',
  'Its My Birthday',
  'Wovsimr Moabiwl',
  'Legend Cocktail Vanilla Sky',
  'Reverse',
  '#000000 Pandora Opens',
  'Nag A Ram',
  'The Cat Is Not Dead',
  'The Answer Is Next The Next Is Answer',
  'Next',
  'Cleopatra Was Queen Today Is',
  'From B1 I Can Go To A3 D2 C3',
  '-.-.—-…',
  '33 + 94 + ?',
  'O degree',
  'If This Level Is Oc Answer Is 63633N',
  'Ppppppp rkbqkbkr',
  'Dont Judge By The Cover 0930289234',
  'Spaceships',
  'Draw Up2 Left1 Up1 Right 0.5 Down 0.5 Right 0.5 Up2 Right 0.5 Down 1 Right 0.5 Up 0.5 Down 1 Left 1 Down 3',
  'Red 1 Yellow 2 Green 3 Bron 4 Blues Pink6 Black 7 I Love This Game',
  'Before You Continue Read This Text First Its Very Important But 1 Guess You Know That Is Hard To Read This Text The Right Way',
  'J F M A M J J A S O N _ O T T F F S S E N _ M T W T F S',
  '14 February – Valets',
  'Up 384 403 Down 20000',
  'Now The Hungry Lion Roars And The Wolf Behowls The Moon Whilst The Heavy Ploughman Snores',
  'Avles Al Ed Yer',
  'XXI VII MCMLXIX',
  'NY 3,14',
  'oooOoooo'
];
var answeArray = [
  '2',
  'Green',
  'Water',
  'R2D2',
  'Yes',
  'Terminator',
  'Lsg',
  '144',
  'Bloodymary',
  'Here',
  '42',
  '55574644',
  'King',
  'Ice',
  'Power',
  'Sheldon',
  'Reject',
  'Orange Juice',
  'Friends',
  'Tennis',
  'Happy Birthday',
  'Mirror',
  'Tomcruise',
  'Esrever none* Answers',
  'Airplane',
  'Anagram',
  'Schrodinger',
  'Next',
  'Answer',
  'Monday / or the current day name',
  'Knight or Horse',
  'Morse',
  '53',
  '360',
  'Cocoon',
  'Chess',
  'Watchmen',
  'Starwars',
  'Cactus',
  'Snooker',
  'Bright',
  'DTS',
  'Nine',
  'Julesverne',
  'Wisdom',
  'Lion',
  'Moonlanding or Moon',
  'Applepie',
  'Mars'
];
